---
title: Testing the Effects of Marijuana Legalization on Crime and Other Drug Usage
  in Seattle and Denver
author: "Benjamin Gaiser and Jeremy Russell"
date: "26 October 2016"
output: pdf_document
bibliography: ./BibTex/LiteratureReviewCitations_SecondAssignment.bib
---
**Research Question:**  
Our research concerns the effects of marijuana legalization in two U.S. states. In 2012, Colorado and Washington legalized recreational marijuana use; and in 2014 Oregon and Alaska followed suit. This November, five other states (Arizona, California, Maine, Massachusetts and Nevada) will consider legalizing the recreational use of marijuana, while four others (Arkansas, Florida, Montana and North Dakota) will decide on medical marijuana initiatives. Opponents of legalization claim legalization leads to an increase in marijuana and other drug use, "increases crime, diminishes traffic safety, harms public health, and lowers teen educational achievement," while advocates "think legalization reduces crime, raises tax revenue, lowers criminal justice expenditures, improves public health, bolsters traffic safety, and stimulates the economy" [@dills2016dose]. As researchers have pointed out though, until now these claims have largely gone unexamined. This recent study concludes that evidence for either side's arguments is lacking, and "the absence of significant adverse consequences is especially striking given the somtimes dire predictions made by legalization opponents" [@dills2016dose]. We would like to test the hypothesis that legalization does not significantly increase crime or other drug usage. We will look more closely at the two state capitals Seattle and Denver to test this.

**Literature Review:**  
Given the general lack of reliable, empirical research on the topic in relation to Washington and Colorado especially, we draw on the results of the Cato Institute's report as it is both recent and highly comparative in nature. Thus, we hope to contribute to the growing body of research on marijuana legalization and policy outcomes. Most research seems to run in a more medical vein. Authors writing for the RAND Corporation argue that it is too soon to adequately address the repurcusions of legalization; or more accurately, that since more data is needed, policy makers must acknowledge the need to work flexibly with issues at hand since what evidence we have is remarkably varying based on which country, state or metro region we analyze [@caulkins2015options]. Another study focuses on the knowledge shared between parents and adolescents from lower-income families and the need for public health campaigns to raise awareness after legalization in Washington state [@mason2015washington]. Researchers found that legalization had a minimal effect on attitudes regarding marijuana; but that after legalization, those who had previously used marijuana before legalization viewed marijuana more favorably than non-users. Our contribution will be to look at initial data to inform stakeholders in this nascent field of policy.  

**Data and Research Methodology:** 
As this is a rather nascent policy field there is as of yet little reliable data (the data that has been gathered in the past was always clouted by the fact that cannabis consumption was illegal and thus statistics were estimations of dark figures). Our assignment will collect the fresh data that is available on cannabis and combine it with already existing data on crime in order to create a new data set that should be able to give a first indication as to whether the link between legalisation and increased crime is really true. 
For this, we use two main sets of data sources: the first is data on recreational cannabis use. Washington State has a very open and good data base, one of the requirements of the ['Washington Initiative 502']('http://www.502data.com'). We will be web-scraping the data with the rvest package [@R-rvest]. Since the 502data site is scripted in Java, we use the phantomjs() function in the RSelenium package [@R-RSelenium] on top of the rvest package. This does unfortunately not work on a Mac. For this reason and because scraping is rather time-consuming, we will provide an unadultered .txt-file of the web-scraped data frame to allow for as much reproducibility as possible (alongside the commands of how we scraped the data). The data lists the names and locations of producers/processors in the state and of retailers including YTD sales and tax revenue. For comparison, we will constrain the data set to King county (Seattle). For Denver's data, we unfortunately do not have access to as open and scrapable data as for Seattle. There is however [monthly marijuana tax data]('https://www.denvergov.org/opendata/search?q=marijuana') from which we can get a crude approximation for the development of use of recreational marijuana in Denver. 
The second set of data sources concerns data on crime. Again the data for Seattle is easier to scrape. While one could potentially download it as a [".csv"-file]('https://data.seattle.gov/Public-Safety/Seattle-Police-Department-Police-Report-Incident/7ais-f98f'), it could also be [scraped]('https://data.seattle.gov/api/views/7ais-f98f/rows.json?accessType=DOWNLOAD') with the jsonlite package [@R-jsonlite]. The data for Denver is yet again harder to get. We will download a a ".csv"-file from [Denver's Open Data Catalog]('https://www.denvergov.org/opendata/dataset/city-and-county-of-denver-crime'). As both data sets are rather large (>80 MB), we will use the readr package [@R-readr] to load the data more quickly. Furthermore, we will only focus on drug-related crime.
Lastly, we also hope to supplement this data with U.S. census data on socio-economic factors per district or county as well.

With regards to the methodology of our assignment, we will begin our analysis with simply descriptive statistics in order to compare both cities and set the scene for further investigation. In a next step, we hope to add a retailer's geo-location to the crime data set in order to analyse whether there is a spatial proximity between retailers of marijuana and drug-related crime. Theoretically, we should see less cannabis-related crime since legalization. Thus we divide the narcotics into two groups, one marijuana-related crimes and one for all others. The socio-economic data from teh U.S. census should us ultimately allow to analyse the differences/similarities between Seattle and Denver conditional on their district-specific characteristics.

\pagebreak

#### References

---
